# Write Kubernates Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: week06:1
        ports:
        - containerPort: 8000
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "postgresql://week06_1ylp_user:MeYUWZJGOqu3OuYzZmwuNuIPJkOFQcot@dpg-crlc6ejtq21c73ecaoa0-a.oregon-postgres.render.com/week06_1ylp"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      